WebApplication1/WebApplication1/Controllers/HomeDevExpressController.cs
using DevExpress.Web.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using DevExpress.Web;
using DevExpress.Web.Demos;
using System.Web.UI.WebControls;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeDevExpressController : Controller
    {
        talentPoolEntities db = new talentPoolEntities();
        // GET: HomeDevExpress
        public ActionResult Index()
        {
            if (Session["UserID"] != null)
            {
                List<tbl_files> filenya = db.tbl_files.ToList();
                ViewData["filenya"] = filenya;
                //string fileName = "Test.docx";
                //using (DevExpress.XtraRichEdit.RichEditDocumentServer srv =
                //    new DevExpress.XtraRichEdit.RichEditDocumentServer())
                //{
                //    DevExpress.XtraRichEdit.API.Native.Document doc = srv.Document;
                //    doc.AppendText("This document is generated by Word Processing Document API");
                //    DevExpress.XtraRichEdit.API.Native.CharacterProperties cp = doc.BeginUpdateCharacters(doc.Paragraphs[0].Range);
                //    cp.ForeColor = System.Drawing.Color.FromArgb(0x83, 0x92, 0x96);
                //    cp.Italic = true;
                //    doc.EndUpdateCharacters(cp);
                //    DevExpress.XtraRichEdit.API.Native.ParagraphProperties pp = doc.BeginUpdateParagraphs(doc.Paragraphs[0].Range);
                //    pp.Alignment = DevExpress.XtraRichEdit.API.Native.ParagraphAlignment.Right;
                //    doc.EndUpdateParagraphs(pp);
                //    srv.SaveDocument(fileName, DevExpress.XtraRichEdit.DocumentFormat.OpenXml);
                //}
                //System.Diagnostics.Process.Start(fileName);
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }
        public ActionResult bukaFile(int id) {
            return View();
        }

        public ActionResult RichEditPartial()
        {
            return PartialView("_RichEditPartial");
        }
    }
}

WebApplication1/WebApplication1/Views/HomeDevExpress/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>@Session["UserName"].ToString()</h2>

@*<table class="table table-bordered">
    <thead>
        <tr>
            <th>File</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in ViewData["filenya"] as IEnumerable<WebApplication1.Models.tbl_files>)
        {
            <tr>
                <td><a href="@Url.Action("bukaFile", "HomeDevExpress", new { id = item.pk_tbl_files_id })">@item.files_name</a></td>
            </tr>
        }
    </tbody>
</table>*@


@using (Html.BeginForm())
{
    @Html.Action("RichEditPartial")
}

WebApplication1/WebApplication1/Views/HomeDevExpress/_RichEditPartial.cshtml
@Html.DevExpress().RichEdit(settings => {
    settings.Name = "RichEdit";
    settings.CallbackRouteValues = new { Controller = "HomeDevExpress", Action = "RichEditPartial" };
    settings.Width = System.Web.UI.WebControls.Unit.Percentage(100);
    settings.WorkDirectory = "Documents";
    settings.Height = 500;
    settings.ReadOnly = false;
    settings.RibbonMode = RichEditRibbonMode.Ribbon;
}).GetHtml()

WebApplication1/WebApplication1/Views/HomeDevExpress/bukaFile.cshtml
@{
    ViewBag.Title = "bukaFile";
}

<h2>bukaFile</h2>